# Generated by Django 5.1.7 on 2025-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='assets/albums/covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='assets/artists/photos/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='assets/playlists/cover/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to='assets/songs/audios/'),
        ),
    ]
