# Generated by Django 5.2 on 2025-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlisttracks",
            old_name="date_added",
            new_name="added_at",
        ),
        migrations.AlterField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(related_name="albums", to="api.artist"),
        ),
        migrations.AlterField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(related_name="tracks", to="api.artist"),
        ),
    ]
