# Generated by Django 5.2 on 2025-04-08 11:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover",
            field=models.ImageField(upload_to=api.models.UploadToPath("cover")),
        ),
        migrations.AlterField(
            model_name="artist",
            name="photo",
            field=models.ImageField(upload_to=api.models.UploadToPath("photo")),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.UploadToPath("cover")
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="audio",
            field=models.FileField(upload_to=api.models.UploadToPath("audio")),
        ),
    ]
